graph TD
  axios --> follow-redirects(^1.15.6)
  axios --> form-data(^4.0.0)
  form-data --> asynckit(^0.4.0)
  form-data --> combined-stream(^1.0.8)
  combined-stream --> delayed-stream(~1.0.0)
  form-data --> mime-types(^2.1.12)
  mime-types --> mime-db(1.52.0)
  axios --> proxy-from-env(^1.1.0)
